### ISSUE TITLE
I'm having trouble setting up the absolute paths for an non-default directory structure

### ISSUE THREAD

**Issue by dschissler** [webpack/less-loader#10]
I've been chipping away at the features and I've had success doing a lot of things with webpack.  One thing that has plagued me for sometime is setting up a directory structure where the conf, bower and node modules are stored in a directory that is a sibling of the directory where my custom modules are stored.

I'm receiving the following error
~~~
ERROR in Entry module not found: Error: Cannot resolve module coffee-loader in /usr/local/webprojects/webpack/app/modules
resolve module coffee-loader in /usr/local/webprojects/webpack/app/modules
~~~

Note that I was successfully working with my node and bower directories being in different places before.  Something about the absolute path situation is messing my project up, since it is not on the same branch.

My project is laid out like the following:
~~~
project
    build
        bower_components
        node_modules
        bower.json
        package.json
        webpack.config.js
    app
        modules (custom/proprietary commonjs modules)
        php
        view (Phalcon Volt partials)
        config (json configs so that socket.io and php can both connect)
        public
            index.php
    dist
        [working stuff will go here and will be fetched in the debug PHP template]

test might go inside of build or on the top level
~~~

I've set it up like this since PHP compilation will be a feature of this framework/scaffold

~~~

var path = require('path');
var webpack = require('webpack');
var console = require('console');

var resolveBowerPath = function(componentPath) {
    return path.join(__dirname, 'bower_components', componentPath);
};
var resolveNodePath = function(componentPath) {
    return path.join(__dirname, 'node_modules', componentPath);
};
var resolveModulePath = function(itemPath) {
    var appPath = path.resolve('../app');
    return path.join(appPath, 'modules', itemPath);
};


console.log(resolveBowerPath(''));
console.log(resolveNodePath(''));
console.log(resolveModulePath(''));
console.log(path.resolve('../app') + '/public/bundle');


module.exports = {
    cache: true,
    context: resolveModulePath(''),

    entry: {
      entryMain: './entryMain'
//      entryLogin: './entryLogin'
    },

    output: {
//        path: __dirname + '/public/bundle',
        path: path.resolve('../app') + '/public/bundle',
        publicPath: '/bundle/',
        filename: "[name].bundle.js",
        chunkFilename: '[id].bundle.js'
    },
    
    resolve: {
//        root: resolveModulePath(''),
        root: [resolveBowerPath(''), resolveNodePath(''), resolveModulePath('')],
        // tells webpack to query these directories for modules
//        modulesDirectories: ['bower_components', 'node_modules'],
        modulesDirectories: [resolveBowerPath(''), resolveNodePath(''), resolveModulePath('')],
//        modulesDirectories: ['./bower_path', './node_modules', resolveModulePath('')],

        alias: {
            lodash: resolveBowerPath('/lodash/dist/lodash'),
            jquery: resolveBowerPath('/jquery/dist/jquery'),
            angular: resolveBowerPath('/angular/angular'),
            angularRouter: resolveBowerPath('/angular-ui-router/release/angular-ui-router'),
            angularCookies: resolveBowerPath('/angular-cookies/angular-cookies'),
            angularResource: resolveBowerPath('/angular-resource/angular-resource'),
        },
        extensions: [
            '',
            '.js', '.coffee',
            '.html', '.jade',
            '.css', '.styl', '.scss', '.less'
        ]        
    },
    plugins: [
        new webpack.ProvidePlugin({
            _: 'lodash',
        }),
        // this plugin makes webpack not only looking for package.json, but also for a bower.json with a main-field
        new webpack.ResolverPlugin([
            new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin("bower.json", ["main"])
        ]),
        new webpack.DefinePlugin({
          VERSION: JSON.stringify('alpha'),
          DEVEL: true
        })
    ],

    module: {
        loaders: [
            // Exports Angular
            { test: /[\/]angular\.js$/, loader: "exports?angular" },
            // Script Loaders
//            { test: /\.coffee$/, loader: "coffee" },
            { test: /\.coffee$/, loader: "coffee-loader" },

            { test: /\.html$/, loader: "html" },
//            { test: /\.jade$/, loader: "jade" },
            { test: /\.jade$/, loader: "template-html-loader" },
            // Style Loaders, style! inlines the css into the bundle files
            { test: /\.css$/, loader: "style!css" },
            { test: /\.scss$/, loader: "style!css!sass" },
            { test: /\.less$/, loader: "style!css!less" },
            { test: /\.styl$/, loader: "style!css!stylus" }
        ]
    }

};
~~~

I've tried a variety of things and this is what I have at the moment.  So, I'm missing something small and obvious right?

**Comment by phnguyen89** [comment]
@dschissler 

Hi,

After searching on Google and tracing through threads, I ended up here.  Did you ever figure out a solution for your original post?  After many configurations, I'm thinking webpack doesn't allow this....

Thanks!

**Comment by dschissler** [comment]
@phnguyen89 Yes I found a solution a long time ago and you can see it in the [gulpfile.webpack.js](https://github.com/perchlayer/webird/blob/master/dev/gulpfile.webpack.js) of my project.  It will likely involve the `context`, `resolve.root`, `resolve.modulesDirectories` and `resolve.resolveLoader`.

**Comment by jhnns** [comment]
So this can be closed? I think it's a rather specific issue and not related to the less-loader.

**Comment by phnguyen89** [comment]
@dschissler Thank you for the prompt reply.  Unfortunately, I wasn't able to achieve a purely webpack.config.js file even with those settings.  I gave up and just added the additional ".babelrc" file (sigh):

    var path = require('path');
    var nodeModulesRoot = path.resolve(__dirname, 'node_modules');
    var distRoot = path.join(__dirname, 'dist');

    module.exports = {
      context: path.resolve('..'),
      entry: [
        './client/index.jsx'
      ],
      module: {
        loaders: [
          {
            exclude: /node_modules/,
            loader: 'babel-loader',
            query: {
              plugins: ['transform-runtime'],
              presets: ['react', 'es2015']
            },
            test: /\.jsx?$/
          }
        ]
      },
      resolve: {
        extensions: ['', '.js', '.jsx'],
        modulesDirectories: [
          'node_modules'
        ],
        root: [
          nodeModulesRoot
        ]
      },
      resolveLoader: {
        root: nodeModulesRoot
      },
      output: {
        path: distRoot,
        publicPath: '/',
        filename: 'bundle.js'
      },
      devServer: {
        contentBase: distRoot
      },
    };

@jhnns Man, you guys are fast.  I only got to replying just now.  I only wanted to ask a question, not raise an issue.  Thanks for closing it!

**Comment by dschissler** [comment]
@phnguyen89 Last time that I tried about two weeks ago I wasn't able to get Babel 6 working with my setup so I've dropped back to version 5 for now.  I'm going to give it a bit of additional time and then I will raise issues about it.  It will be involved and difficult to figure out what is happening so I'm putting it off as long as possible.

**Comment by phnguyen89** [comment]
@dschissler I'm glad that others are having issue :)  ".babelrc" is actually more portable than writing it in webpack lingo, so it's all how you look at the problem haha.  The only way I was able to make it work in webpack.config.js is to use absolute paths in the module.loaders's query.plugins and query.presets.  I suppose that's fine, but feels quite redundant.

**Comment by dschissler** [comment]
@phnguyen89 I just upgraded to postcss 5 and I had to re-specify in the plugin which paths to look inside.
