### ISSUE TITLE
Unable to resolve module error and reproduction of issue

### ISSUE THREAD

**Issue by jsonnull** [webpack/less-loader#109]
I've run into a bunch of issues attempting to use `@import` and `url()` when adding CSS modules to a current project and using `less-loader`.

It looks like a lot of people have this error:
- https://github.com/webpack/less-loader/issues/76 (same issue?)
- https://github.com/webpack/less-loader/issues/101
- https://github.com/webpack/less-loader/issues/93
- https://github.com/webpack/less-loader/issues/85 (connected issue?)

... and so on.

I absolutely cannot get any kind of relative file load to work. I've attempted to create a minimal reproducible test case for the issue. The repository is located here: https://github.com/jsonnull/less-modules-resolve.

`npm install` and `npm run build` to see the issue.

```
ERROR in ./~/css-loader?modules!./~/less-loader?sourceMap!./src/index.less
Module not found: Error: Can't resolve 'material-design-icons/MaterialIcons-Regular.ttf' in '/Users/jsonnull/less-modules-resolve/src'
 @ ./~/css-loader?modules!./~/less-loader?sourceMap!./src/index.less 6:470-528
 @ ./src/index.less
 @ ./src/index.js
```

See below, the file is clearly present:

```
├── dist
│   └── build.js
├── npm-debug.log
├── package.json
├── src
│   ├── index.js
│   ├── index.less
│   └── material-design-icons
│       ├── LICENSE
│       ├── MaterialIcons-Regular.eot
│       ├── MaterialIcons-Regular.ijmap
│       ├── MaterialIcons-Regular.svg
│       ├── MaterialIcons-Regular.ttf
│       ├── MaterialIcons-Regular.woff
│       ├── MaterialIcons-Regular.woff2
│       ├── README.md
│       ├── codepoints
│       └── material-icons.less
└── webpack.config.js
```

I've tried every combination for the less file import as well as the `url()` import I can think of...
- `file` - I think this one should work?
- `./file` - I think this one should definitely work
- `~file` - I think this one should not work
- `/file` - I think this one should not work

And, anyways, none of these methods work.

**Assuming this is possible, how can the repository above be fixed so that all issues are resolved using the current directory structure?** Otherwise, are there really combinations of relative paths that are completely impossible to use for importing?

From scrounging through issues it really does seem like nobody has a clear understanding of what this issue is or how to fix it. If we can come up with a clear answer for this issue for why it doesn't work and how to fix, hopefully others can learn from this and we can come up with good documentation for how to avoid this issue.

**Comment by tamer1an** [comment]
+1

**Comment by jhnns** [comment]
Thx for the detailed bug report. With your description and the minimal test example I was able to spot the issue very quickly 👍 

Unfortunately, that's a really tricky one, let me explain it:

- First, webpack encounters the `index.less` and passes it to less-loader
- The less-loader passes the file to less
- Less parses the file and discovers the `@import` statement. Since nested imports are legal less, less is resolving the `material-icons.less` with the help of the less-loader
- Now less has all the less files and compiles them down to CSS
- During this compile step, less rewrites all urls so that the output contains the correct path. This is because the less-loader [sets the `relativeUrls` option](https://github.com/webpack/less-loader/blob/7ab6a2ef7d17e1ebaa9d15e8cf79fc0120c21523/index.js#L26). This option is very useful, since it allows you to write your less files in a modular way, just reference your images and the final CSS contains valid urls. The urls look like this:

```less
// before compilation
url('MaterialIcons-Regular.eot')
// after compilation
url('material-design-icons/MaterialIcons-Regular.eot')
// all urls are relative to index.less
```

- This CSS is now passed to the css-loader with the modules option enabled. If a CSS module contains an import statement that does not start with a dot, it is considered to be a module request and webpack will search in `node_modules` for it.
- If less had rewritten the url to `url('./material-design-icons/MaterialIcons-Regular.eot')` everything would work just fine.

It basically boils down to LESS + relativeUrls: true + CSS modules is not compatible. Either you convince less to rewrite their urls so that relative urls start with a dot, or you override the `relativeUrls` option in the less-loader or you get rid of less at all (I think, in combination with CSS modules less is not really necessary).

**Comment by jsonnull** [comment]
@jhnns Thanks for looking into this!

I'm going to close this issue, but I've left the repository in place in case anybody else comes across this issue.

**Comment by MrBoolean** [comment]
👍

**Comment by jsonnull** [comment]
@MrBoolean unfortunately this problem is not going away any time soon. As stated above "It basically boils down to LESS + relativeUrls: true + CSS modules is not compatible"

I migrated away from LESS because I needed CSS modules and relative imports, and CSS formats are relatively interchangeable these days.

**Comment by chardlau** [comment]
@jsonnull 
I found that if wrap the less file with a folder and prepend '../' when using url() can work.
files distributes like below:

module_root/
    index.js (Here, use import './css/index.less')
    css/
        index.less  (Here, use url('../assets/test.eot'))
    assets/
       test.eot

It looks so ugly, but i work.

**Comment by txiaocao** [comment]
Haha, I resolve this; this is hack
i create images.css,and require the css files,and use
the code 
```js
private images = require("./images");
this.images.loader
``` 
```css
.loader{
background-image: url("./301.gif");
}
```

**Comment by ganxunzou** [comment]
@chardlau think you

**Comment by limichange** [comment]
There is fine. 🤔  
```
.loader{
   background-image: url("\./301.gif");
}
```

**Comment by rally25rs** [comment]
> During this compile step, less rewrites all urls so that the output contains the correct path.

@jhnns is there a way to disable this? When importing a lot of 3rd party CSS files, they have `url()`s set to where the file _will be hosted_ not where it is on disk. These may not be resolvable by any loader, and the files can't be edited (they come from other dependencies).

`css-loader` can be passed `url: false` to stop processing those URLs, but `less-loader` always changes them, making them incorrect at runtime.

**Comment by rally25rs** [comment]
For those that come across this issue and find that it completely blocks them from using less-loader... for example I have styling from some 3rd party libs that have `url(` references to files that don't exist on disk, like `chosen-bootstrap` references images that ship with `chosen` but aren't included in `chosen-bootstrap` itself.

You can disable all this URL mangling with `relativeUrls: false` on less-loader, and `url: false` on css-loader.

```
      {
        test: /\.less/,
        use: [{
          loader: 'style-loader'
        }, {
          loader: 'css-loader',
          options: {url: false, sourceMap: true}
        }, {
          loader: 'less-loader',
          options: {relativeUrls: false, sourceMap: true}
        }]
      },
```

This makes all `url()` entries stay as they were in the original less and css source (unchanged) and webpack will no longer try to resolve them. This also means that you no longer need `file-loader` or `url-loader` to process each of those files, however you also need a build step to copy the static assets into your own deploy directory where the web server can get to them. It also means there will be hot-reloading for the less files, but not for fonts and images.

This was fine for me, as I was mostly just wanted the less file hot reloading.

**Comment by garygreen** [comment]
@rally25rs thanks so much for that - it's worth noting that if you only need to do this for certain files you can change the rule so it only uses that loader with those custom options if needed. I'm a total noob when it comes to Webpack, so not sure if I'm doing it right but it seems to be working good for me.

Here's my current webpack config:

```php
       {
           test: /\.less$/,
           exclude: /site.less$/,
           use: ExtractTextPlugin.extract({
               use: ['css-loader', 'less-loader'],
               fallback: 'style-loader'
           })
       },
       // Custom less compiler for frontend site less.
       // This basically just turns off resolving of url() as they should all be
       // in the public_html so don't need to be resolved, and would cause problems if they are.
       {
           test: /site.less$/,
           use: ExtractTextPlugin.extract({
               use: [{
                   loader: 'css-loader',
                   options: {url: false, sourceMap: true}
               }, {
                   loader: 'less-loader',
                   options: {relativeUrls: false, sourceMap: true}
               }],
               fallback: 'style-loader'
           })
       },
```

**Comment by mqliutie** [comment]
@garygreen Thanks for your comment

**Comment by boylec** [comment]
I got this to work without needing to turn off relativeUrls by making use of 'url-loader' for fonts/images:

For example:
```
           {
                test: /\.(woff(2)?|ttf|eot|svg)(\?v=\d+\.\d+\.\d+)?$/,
                enforce: "pre", // preload the jshint loader
                use: [{
                    loader: "url-loader",
                    options: {
                        query: { limit: 25000 }
                    }
                }]
            },
            {
                test: /\.(png|jpg|jpeg|gif|svg)$/, // include .ts files
                enforce: "pre", // preload the jshint loader
                exclude: /node_modules/, // exclude any and all files in the node_modules folder
                use: [{
                    loader: "url-loader",
                    options: {
                        query: { limit: 25000 }
                    }
                }]
            }
```
You could probably combine the loaders but I wanted them to behave slightly differently - ie `exclude: /node_modules/`.

**Comment by matthew-dean** [comment]
Does the `--rewrite-urls=local` option resolve this issue? http://lesscss.org/usage/#less-options-rewrite-urls

**Comment by matthew-dean** [comment]
Also, as noted in #276, no special `~` syntax should be needed to load styles from the node_modules folder. Less-loader is actually breaking Less module-loading functionality, but maybe that's by design. (I'm not a Webpack expert.)

**Comment by jhnns** [comment]
For future reference: passing `{rewriteUrls: "local"}` as Less option should fix the problem. Check out the [Less documentation](http://lesscss.org/usage/#less-options-rewrite-urls) for more information.

**Comment by manugb** [comment]
For remote @import urls check this out
https://github.com/less/less.js/issues/3188#issuecomment-374690630

**Comment by kanishka-malhotra** [comment]
Following configuration helped me resolve the issue with relative URLs due to less-loader + CSS modules ([mentioned here](https://github.com/webpack-contrib/less-loader/issues/109#issuecomment-253797335))

```
{
  test: /\.less$/,
  use: [
    {
      loader: MiniCssExtractPlugin.loader,
      options: {
        publicPath: '/'  // NOTE: this option does the charm to add `/` in front of all relative assets (don't use `./`)
      }
    },
    {
      loader: 'css-loader',
      options: {
        importLoaders: 2,
      },
    },
    {
      loader: 'postcss-loader',
      options: {
        postcssOptions: {
          config: path.resolve(__dirname, 'postcss.config.js'),
        },
      },
    },
    {
      loader: 'less-loader',
    },
  ],
}
```

Hope this helps!
