### ISSUE TITLE
Variable not accessible using Require includes.

### ISSUE THREAD

**Issue by ronnross** [webpack/less-loader#34]
I'm using Wepack and the Less-loader to package all my JavaScript and CSS in a single file. I'm using the require syntax to import my LESS. For example, 
`require('base.less');`
`require('more.less');`

Unfortunately, any variables defined in base are not accessible in any file required after it. I would think this would work and be resolved by the loader. Am I mistaken?

**Comment by sokra** [comment]
> Am I mistaken?

yes, this doesn't work.

you need to `@import "base.less"` in `more.less`.

**Comment by ronnross** [comment]
ok that clears it up. Thanks
