### ISSUE TITLE
Require not finding .less files

### ISSUE THREAD

**Issue by jagandecapri** [webpack/less-loader#45]
I have an app with the following structure

```
app/
build/
styles/
  - app.less
...
client.js
webpack.config.js
...
```

client.js is the entry point for Webpack config. Inside client.js, I am requiring app.less by `require('./styles/app.less)`.

Snippet of the config.js:

```javascript
// client.js
import app from './app';

require('./styles/app.less');
......
```

Snippet of webpack.config.js:

```javascript
// webpack.config.js
.....
entry: './client.js',
output: {
      path: './build/dist',
      publicPath: '/public/dist/',
      filename: '[name].js',
      chunkFilename: '[id].js'
 },
 module: {
       loaders: [{
              test: /\.less$/,
              loader: ExtractTextPlugin.extract('style-loader', 'css-loader!less-loader')
              }, {
 .....
```
When I build the files with Webpack, there are no .css files that are compiled inside my **build/dist/** folder. In the browser, it shows " cannot find module './styles/app.less' "

Is the mixing of ES6 imports and require causing the problem?

Any help would be greatly appreciated. Thanks.

**Comment by jagandecapri** [comment]
Found the issue. I was missing the css-loader. 

Trivial problem but it took me so long to find because I was using Gulp to run webpack and it didn't print any error even when I set debug option to be true. Not sure why.

Anyway, I installed webpack as a global module and ran the webpack in CLI. I saw this error when running in CLI and installed the deps as needed.

Hope this helps others who are starting out with build systems etc. ;)

**Comment by akum32** [comment]
Thanks for sharing...had the same issue.

**Comment by jagandecapri** [comment]
@akum32 Welcome :+1:

**Comment by walkerrandolphsmith** [comment]
Ah, I had the same issue. XD

**Comment by Yunlong2cn** [comment]
I have trouble with the same issue -_- !
webpack config is:
{
	test: /\.less$/, 
	loader: 'style-loader!css-loader!less-loader'
}
but it always show me cant find module 'less'

**Comment by kl2karpenko** [comment]
install 'less' in your project using npm install less --save-dev

**Comment by michaeldick** [comment]
@kl2karpenko thanks for the tip, it seems like a basic first step that no tutorial ever thought to mention. Glad I googled and found your tip on installing LESS :).

Thanks!

**Comment by kl2karpenko** [comment]
Looks like a lot of people think that this is too easy but I also was stuck at this point for some time =)
