### ISSUE TITLE
modifyVar not being passed from query string

### ISSUE THREAD

**Issue by JamesHageman** [webpack/less-loader#48]
I am trying to inject variables into less-loader with the modifyVars option. The loader configuration looks something like this: 
```
ExtractTextPlugin.extract('style-loader',
                'css?module&importLoaders=2&localIdentName=[hash:base64:5]' +
                '!postcss!less?modifyVars="theme-main=red"');
```
I expected this to set the `@theme-main` variable to `red`, but I got this error instead:
```
ERROR in ../~/css-loader?module&importLoaders=2&localIdentName=[path][name]---[local]---[hash:base64:5]
!../~/postcss-loader!../~/less-loader?modifyVar="theme-main=red"
!./components/stylesheets/Tabs.less
    Module build failed: variable @theme-main is undefined
     @ /path/to/variables.less (line 62, column 16)
     near lines:

       @brand-primary: @theme-main;

```
Did I make a mistake in the query string syntax? What is the accepted way of passing parameterized options into less with the loader?

**Comment by JamesHageman** [comment]
@jhnns, @sokra any suggestions?

**Comment by jhnns** [comment]
Sorry for the delayed answer.

Have you tried to escape the parameters via `encodeURIComponent`? Like:

```javascript
ExtractTextPlugin.extract('style-loader',
                'css?module&importLoaders=2&localIdentName=[hash:base64:5]' +
                '!postcss!less?modifyVars=' + encodeURIComponent('theme-main=red'));
```

The equal-sign is probably interpreted as value delimiter.

**Comment by jhnns** [comment]
Probably related to #46

**Comment by jhnns** [comment]
To avoid escaping hell you can also just use `JSON.stringify()` to [stringify your config as JSON](http://webpack.github.io/docs/using-loaders.html#query-parameters).

**Comment by unodgs** [comment]
modifyVars is passed. For example I use following command: 
```loader: ExtractTextPlugin.extract("style-loader", 'css-loader!less-loader?{"modifyVars":{"icon-font-path":"\'../../fonts\'"}}'),```

**Comment by jhnns** [comment]
Thx @unodgs 
@JamesHageman If the problem still exists, please re-open

**Comment by Asgator** [comment]
Again dont work if i doo 
```
loader: ExtractTextPlugin.extract("style-loader", 'css-loader!less-loader?{"modifyVars":{"icon-font-path":"\'../../fonts\'"}}'),
```
