### ISSUE TITLE
less dependency missing

### ISSUE THREAD

**Issue by unimonkiez** [webpack/less-loader#66]
Hey,
You fixed less as a peer dependency issue a month ago ([here](https://github.com/webpack/less-loader/commit/d172f77476f752f802d2f041b5b6ba5e2551d913)), but didn't make a tag out of it.

I'm using library called [font-awesome-webpack](https://github.com/gowravshekar/font-awesome-webpack/) which uses your latest tag but because of it, it won't work on npm3.

Please upgrade, and thanks in advance.

**Comment by vzaidman** [comment]
same problem here

**Comment by unimonkiez** [comment]
@vzaidman and everybody else looking at this error listen up.
I've seen they reverted the removal of peerDependency, It's up to you to install less on your project.
For the whole conversation of why go here #66
