### ISSUE TITLE
UNMET PEER DEPENDENCY less@^2.3.1

### ISSUE THREAD

**Issue by oliwerhelsen** [webpack/less-loader#68]
Hey,

I keep getting "UNMET PEER DEPENDENCY less@^2.3.1" when i try to install less-loader via npm. 

Any idea for a solution?

Best regards
Oliwer H.

**Comment by mmjurov** [comment]
Having the same issue. How do you solve it?

node v5.4.1
npm 3.3.12

**Comment by guocheng** [comment]
@mmjurov it means less itself is not installed locally. Just do this:

`npm install --save-dev less`

**Comment by mmjurov** [comment]
@guocheng, thank you for your reply, but i still don't understand ... 

**less** is a **dependency** of **less-loader**. npm must install all dependencies of that package when i type `npm install less-loader`, or it's not?
If i install less additionally with additional command, or before less-loader installation, less works fine and not cause any warnings, but i'm waiting that npm will install less with less-loader together as a dependency. 
Is that correct behaviour of npm, if it didn't install less with less-loader together? (sorry for that noob question, if it is, and for my bad english :) )

**Comment by guocheng** [comment]
@mmjurov I thought npm would download the dependency too, but that is not the case with npm 3+ [check out this post](https://github.com/npm/npm/issues/6565) 

Your npm version is 3.3 so that's why

**Comment by mmjurov** [comment]
Oh, many thanks! it explains everything
