### ISSUE TITLE
Unexpected token {

### ISSUE THREAD

**Issue by stenrap** [webpack/less-loader#98]
My very simple .less file is generating an error from webpack:

> Module parse failed: /Users/rob/code/wordsfromwords/src/front/less/wfw.less Line 1: Unexpected token {
> You may need an appropriate loader to handle this file type.

Here's my config:

```javascript
var path = require('path');

module.exports = {
    entry: {
        wfw: './src/front/js/wfw'
    },
    modules: {
        loaders: [
            {
                test: /\.less$/,
                loader: 'style!css!less'
            }
        ]
    },
    output: {
        chunkFilename: '[id].bundle.min.js',
        filename:      '[name].bundle.min.js',
        path:          __dirname + '/public/build/',
        publicPath:    '/public/build/'
    },
    resolve: {
        extensions: ['', '.js', '.less'],
        root: [
            path.join(__dirname, 'node_modules')
        ]
    },
    resolveLoader: {
        root: path.join(__dirname, 'node_modules')
    }
};
```

Here's my entry JavaScript file:

```javascript
require('../less/wfw');
```

And here's my .less file:

```less
body {
    font-family: "Helvetica Neue";
    font-size: 22px;
}
```

What am I doing wrong?

**Comment by simonbuehler** [comment]
@stenrap you remember the solution?

**Comment by stenrap** [comment]
@simonbuehler: I think I had simply forgotten to `npm install less-loader` (which is why the error was: "You may need an appropriate loader to handle this file type.").

**Comment by jhnns** [comment]
> I think I had simply forgotten to npm install less-loader

That would give an error like `Can't resolve less-loader`.

> Module parse failed:

This means that the result of the loader pipeline is not JS. Maybe you've forgotten the css-loader or the raw-loader? @simonbuehler Or maybe you have an exclude option that excludes this file from the loader pipeline?

**Comment by simonbuehler** [comment]
it was actually a missing css - and - less-loader ...
